apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: devops-lab
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://host.minikube.internal:9090
      access: proxy
      isDefault: true
